// <auto-generated />
using DataBaseManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBase.Migrations
{
    [DbContext(typeof(VkDbContext))]
    [Migration("20180620093520_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("DataBaseManager.Entities.PostImagesTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image");

                    b.Property<int>("PostItemId");

                    b.HasKey("Id");

                    b.HasIndex("PostItemId");

                    b.ToTable("PostImagesTable");
                });

            modelBuilder.Entity("DataBaseManager.Entities.PostItemTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("PostId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("PostItemTable");
                });

            modelBuilder.Entity("DataBaseManager.Entities.PostLinksTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link");

                    b.Property<int>("PostItemId");

                    b.HasKey("Id");

                    b.HasIndex("PostItemId");

                    b.ToTable("PostLinksTable");
                });

            modelBuilder.Entity("DataBaseManager.Entities.PostImagesTable", b =>
                {
                    b.HasOne("DataBaseManager.Entities.PostItemTable", "PostItem")
                        .WithMany("PostImages")
                        .HasForeignKey("PostItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataBaseManager.Entities.PostLinksTable", b =>
                {
                    b.HasOne("DataBaseManager.Entities.PostItemTable", "PostItem")
                        .WithMany("PostLinks")
                        .HasForeignKey("PostItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
